[2024-05-14T06:25:13.544+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-14T06:23:47.070551+00:00 [queued]>
[2024-05-14T06:25:13.578+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-14T06:23:47.070551+00:00 [queued]>
[2024-05-14T06:25:13.580+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-14T06:25:13.612+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_and_clean_data_task> on 2024-05-14 06:23:47.070551+00:00
[2024-05-14T06:25:13.625+0000] {standard_task_runner.py:60} INFO - Started process 875 to run task
[2024-05-14T06:25:13.630+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_and_clean_data_task', 'manual__2024-05-14T06:23:47.070551+00:00', '--job-id', '916', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmpsy1yygg2']
[2024-05-14T06:25:13.633+0000] {standard_task_runner.py:88} INFO - Job 916: Subtask process_and_clean_data_task
[2024-05-14T06:25:13.706+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-14T06:23:47.070551+00:00 [running]> on host 87b4d1457810
[2024-05-14T06:25:13.839+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_and_clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T06:23:47.070551+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T06:23:47.070551+00:00'
[2024-05-14T06:25:15.881+0000] {logging_mixin.py:188} INFO - Table created successfully
[2024-05-14T06:25:15.900+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 262, in process_and_clean_data
    cur.execute(insert_query, values)
psycopg2.errors.DatatypeMismatch: column "Time_added" is of type timestamp without time zone but expression is of type time without time zone
LINE 3: ...47, 'Moderate', '2024-05-11T00:00:00'::timestamp, '00:00:00'...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[2024-05-14T06:25:15.917+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=process_and_clean_data_task, execution_date=20240514T062347, start_date=20240514T062513, end_date=20240514T062515
[2024-05-14T06:25:15.942+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 916 for task process_and_clean_data_task (column "Time_added" is of type timestamp without time zone but expression is of type time without time zone
LINE 3: ...47, 'Moderate', '2024-05-11T00:00:00'::timestamp, '00:00:00'...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
; 875)
[2024-05-14T06:25:15.977+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-14T06:25:16.003+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
