[2024-05-11T14:21:44.523+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.postgres_operator manual__2024-05-11T14:20:02.868353+00:00 [queued]>
[2024-05-11T14:21:44.536+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.postgres_operator manual__2024-05-11T14:20:02.868353+00:00 [queued]>
[2024-05-11T14:21:44.537+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-11T14:21:44.562+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): postgres_operator> on 2024-05-11 14:20:02.868353+00:00
[2024-05-11T14:21:44.570+0000] {standard_task_runner.py:60} INFO - Started process 771 to run task
[2024-05-11T14:21:44.575+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'postgres_operator', 'manual__2024-05-11T14:20:02.868353+00:00', '--job-id', '719', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmpapf6x4xu']
[2024-05-11T14:21:44.579+0000] {standard_task_runner.py:88} INFO - Job 719: Subtask postgres_operator
[2024-05-11T14:21:44.645+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.postgres_operator manual__2024-05-11T14:20:02.868353+00:00 [running]> on host 87b4d1457810
[2024-05-11T14:21:44.745+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='postgres_operator' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T14:20:02.868353+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T14:20:02.868353+00:00'
[2024-05-11T14:21:44.747+0000] {sql.py:276} INFO - Executing: 
    INSERT INTO songs ("Track ID", "Track Name", "Artist Name", "Album Name", "Release Date", "Type of Album", "Popularity", "Popularity Category", "Date_added", "Time_added")
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    
[2024-05-11T14:21:44.762+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-11T14:21:44.777+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-11T14:21:44.835+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"

[2024-05-11T14:21:44.849+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=postgres_operator, execution_date=20240511T142002, start_date=20240511T142144, end_date=20240511T142144
[2024-05-11T14:21:44.867+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 719 for task postgres_operator (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"
; 771)
[2024-05-11T14:21:44.909+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T14:21:44.941+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
