[2024-05-11T12:59:08.698+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T12:57:38.631106+00:00 [queued]>
[2024-05-11T12:59:08.714+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T12:57:38.631106+00:00 [queued]>
[2024-05-11T12:59:08.716+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-11T12:59:08.739+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_and_clean_data_task> on 2024-05-11 12:57:38.631106+00:00
[2024-05-11T12:59:08.751+0000] {standard_task_runner.py:60} INFO - Started process 407 to run task
[2024-05-11T12:59:08.755+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_and_clean_data_task', 'manual__2024-05-11T12:57:38.631106+00:00', '--job-id', '642', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmp8fmva1rn']
[2024-05-11T12:59:08.757+0000] {standard_task_runner.py:88} INFO - Job 642: Subtask process_and_clean_data_task
[2024-05-11T12:59:08.854+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T12:57:38.631106+00:00 [running]> on host 8d7ea4aa6981
[2024-05-11T12:59:09.038+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_and_clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T12:57:38.631106+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T12:57:38.631106+00:00'
[2024-05-11T12:59:10.897+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 225, in process_and_clean_data
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-05-11T12:59:10.915+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=process_and_clean_data_task, execution_date=20240511T125738, start_date=20240511T125908, end_date=20240511T125910
[2024-05-11T12:59:10.937+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 642 for task process_and_clean_data_task (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 407)
[2024-05-11T12:59:10.984+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T12:59:11.007+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
