[2024-05-07T14:03:35.828+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-07T14:02:10.731202+00:00 [queued]>
[2024-05-07T14:03:35.839+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-07T14:02:10.731202+00:00 [queued]>
[2024-05-07T14:03:35.840+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-07T14:03:35.856+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_and_clean_data_task> on 2024-05-07 14:02:10.731202+00:00
[2024-05-07T14:03:35.862+0000] {standard_task_runner.py:60} INFO - Started process 1572 to run task
[2024-05-07T14:03:35.865+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_and_clean_data_task', 'manual__2024-05-07T14:02:10.731202+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmpxjs_7i8l']
[2024-05-07T14:03:35.867+0000] {standard_task_runner.py:88} INFO - Job 380: Subtask process_and_clean_data_task
[2024-05-07T14:03:35.922+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-07T14:02:10.731202+00:00 [running]> on host 8aebc95d8de6
[2024-05-07T14:03:36.017+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_and_clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T14:02:10.731202+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-07T14:02:10.731202+00:00'
[2024-05-07T14:03:37.765+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 267, in process_and_clean_data
    df['Popularity Category'] = pd.cut(df['Popularity'], bins=popularity_bins, labels=popularity_labels, right=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'Popularity'
[2024-05-07T14:03:37.789+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=process_and_clean_data_task, execution_date=20240507T140210, start_date=20240507T140335, end_date=20240507T140337
[2024-05-07T14:03:37.806+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 380 for task process_and_clean_data_task ('Popularity'; 1572)
[2024-05-07T14:03:37.852+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-07T14:03:37.876+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
