[2024-05-08T16:04:50.384+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-08T23:03:07+07:00 [queued]>
[2024-05-08T16:04:50.400+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-08T23:03:07+07:00 [queued]>
[2024-05-08T16:04:50.401+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-08T16:04:50.421+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_and_clean_data_task> on 2024-05-08 16:03:07+00:00
[2024-05-08T16:04:50.429+0000] {standard_task_runner.py:60} INFO - Started process 1972 to run task
[2024-05-08T16:04:50.433+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_and_clean_data_task', 'manual__2024-05-08T23:03:07+07:00', '--job-id', '545', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmpmgx9cedk']
[2024-05-08T16:04:50.436+0000] {standard_task_runner.py:88} INFO - Job 545: Subtask process_and_clean_data_task
[2024-05-08T16:04:50.495+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-08T23:03:07+07:00 [running]> on host 8aebc95d8de6
[2024-05-08T16:04:50.596+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_and_clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T16:03:07+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-08T23:03:07+07:00'
[2024-05-08T16:04:51.992+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 222, in process_and_clean_data
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-05-08T16:04:52.012+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=process_and_clean_data_task, execution_date=20240508T160307, start_date=20240508T160450, end_date=20240508T160452
[2024-05-08T16:04:52.047+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 545 for task process_and_clean_data_task (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 1972)
[2024-05-08T16:04:52.096+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-08T16:04:52.118+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
