[2024-05-11T15:54:36.137+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T15:53:06.004524+00:00 [queued]>
[2024-05-11T15:54:36.152+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T15:53:06.004524+00:00 [queued]>
[2024-05-11T15:54:36.153+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-11T15:54:36.171+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_and_clean_data_task> on 2024-05-11 15:53:06.004524+00:00
[2024-05-11T15:54:36.181+0000] {standard_task_runner.py:60} INFO - Started process 2372 to run task
[2024-05-11T15:54:36.185+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_and_clean_data_task', 'manual__2024-05-11T15:53:06.004524+00:00', '--job-id', '801', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmp9fo67pxz']
[2024-05-11T15:54:36.187+0000] {standard_task_runner.py:88} INFO - Job 801: Subtask process_and_clean_data_task
[2024-05-11T15:54:36.245+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T15:53:06.004524+00:00 [running]> on host 87b4d1457810
[2024-05-11T15:54:36.343+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_and_clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T15:53:06.004524+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T15:53:06.004524+00:00'
[2024-05-11T15:54:40.451+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 341, in process_and_clean_data
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres_localhost" to address: Name or service not known

[2024-05-11T15:54:40.470+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=process_and_clean_data_task, execution_date=20240511T155306, start_date=20240511T155436, end_date=20240511T155440
[2024-05-11T15:54:40.493+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 801 for task process_and_clean_data_task (could not translate host name "postgres_localhost" to address: Name or service not known
; 2372)
[2024-05-11T15:54:40.541+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T15:54:40.566+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
