[2024-05-11T14:30:38.637+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.postgres_operator manual__2024-05-11T14:30:13.404658+00:00 [queued]>
[2024-05-11T14:30:38.650+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.postgres_operator manual__2024-05-11T14:30:13.404658+00:00 [queued]>
[2024-05-11T14:30:38.651+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-11T14:30:38.667+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): postgres_operator> on 2024-05-11 14:30:13.404658+00:00
[2024-05-11T14:30:38.673+0000] {standard_task_runner.py:60} INFO - Started process 948 to run task
[2024-05-11T14:30:38.679+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'postgres_operator', 'manual__2024-05-11T14:30:13.404658+00:00', '--job-id', '735', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmptgu9cj_i']
[2024-05-11T14:30:38.681+0000] {standard_task_runner.py:88} INFO - Job 735: Subtask postgres_operator
[2024-05-11T14:30:38.747+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.postgres_operator manual__2024-05-11T14:30:13.404658+00:00 [running]> on host 87b4d1457810
[2024-05-11T14:30:38.868+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='postgres_operator' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T14:30:13.404658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T14:30:13.404658+00:00'
[2024-05-11T14:30:38.871+0000] {sql.py:276} INFO - Executing: 
    INSERT INTO songs ("Track ID", "Track Name", "Artist Name", "Album Name", "Release Date", "Type of Album", "Popularity", "Popularity Category", "Date_added", "Time_added")
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    
[2024-05-11T14:30:38.885+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-11T14:30:38.907+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-11T14:30:38.980+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"

[2024-05-11T14:30:38.999+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=postgres_operator, execution_date=20240511T143013, start_date=20240511T143038, end_date=20240511T143038
[2024-05-11T14:30:39.022+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 735 for task postgres_operator (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"
; 948)
[2024-05-11T14:30:39.053+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T14:30:39.080+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
