[2024-05-11T16:14:51.251+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T16:14:31.502288+00:00 [queued]>
[2024-05-11T16:14:51.271+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T16:14:31.502288+00:00 [queued]>
[2024-05-11T16:14:51.272+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-11T16:14:51.299+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_and_clean_data_task> on 2024-05-11 16:14:31.502288+00:00
[2024-05-11T16:14:51.310+0000] {standard_task_runner.py:60} INFO - Started process 2778 to run task
[2024-05-11T16:14:51.317+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_and_clean_data_task', 'manual__2024-05-11T16:14:31.502288+00:00', '--job-id', '840', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmplt6mqkh5']
[2024-05-11T16:14:51.320+0000] {standard_task_runner.py:88} INFO - Job 840: Subtask process_and_clean_data_task
[2024-05-11T16:14:51.472+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-11T16:14:31.502288+00:00 [running]> on host 87b4d1457810
[2024-05-11T16:14:51.731+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_and_clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T16:14:31.502288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T16:14:31.502288+00:00'
[2024-05-11T16:14:52.631+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 166, in process_and_clean_data
    playlist_id = result["id"]
TypeError: list indices must be integers or slices, not str
[2024-05-11T16:14:52.676+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=process_and_clean_data_task, execution_date=20240511T161431, start_date=20240511T161451, end_date=20240511T161452
[2024-05-11T16:14:52.707+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 840 for task process_and_clean_data_task (list indices must be integers or slices, not str; 2778)
[2024-05-11T16:14:52.744+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T16:14:52.823+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
