[2024-05-06T15:12:52.836+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.clean_transform_data manual__2024-05-06T15:11:25.838537+00:00 [queued]>
[2024-05-06T15:12:52.846+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.clean_transform_data manual__2024-05-06T15:11:25.838537+00:00 [queued]>
[2024-05-06T15:12:52.848+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-06T15:12:52.863+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): clean_transform_data> on 2024-05-06 15:11:25.838537+00:00
[2024-05-06T15:12:52.872+0000] {standard_task_runner.py:60} INFO - Started process 3356 to run task
[2024-05-06T15:12:52.875+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'clean_transform_data', 'manual__2024-05-06T15:11:25.838537+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmp70sbpbzf']
[2024-05-06T15:12:52.876+0000] {standard_task_runner.py:88} INFO - Job 212: Subtask clean_transform_data
[2024-05-06T15:12:52.927+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.clean_transform_data manual__2024-05-06T15:11:25.838537+00:00 [running]> on host 903c75f80f15
[2024-05-06T15:12:53.030+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='clean_transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T15:11:25.838537+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T15:11:25.838537+00:00'
[2024-05-06T15:12:53.043+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 309, in clean_and_transform_data
    df = df.dropna().reset_index(drop=True)
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-05-06T15:12:53.058+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=clean_transform_data, execution_date=20240506T151125, start_date=20240506T151252, end_date=20240506T151253
[2024-05-06T15:12:53.073+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 212 for task clean_transform_data ('NoneType' object has no attribute 'dropna'; 3356)
[2024-05-06T15:12:53.089+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T15:12:53.117+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
